# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
#      interval: "weekly"
      interval: "monthly"
      day: "monday"
      time: "12:00"
      timezone: "UTC"
    commit-message:
      prefix: ⬆
  # Pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # Include a list of updated dependencies
    # with a prefix determined by the dependency group
    commit-message:
      prefix: 📦
